/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 main_ground.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Main_Ground(props) {
  const { nodes, materials } = useGLTF('/models/main_ground.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-64.22, 30.389, 11.555]} scale={[0.456, 0.625, 0.456]}>
        <mesh geometry={nodes.Sphere001.geometry} material={materials.tree1} />
        <mesh geometry={nodes.Sphere001_1.geometry} material={materials.tree2} />
        <mesh geometry={nodes.Sphere001_2.geometry} material={materials.tree3} />
        <mesh geometry={nodes.Sphere001_3.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Sphere001_4.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Sphere001_5.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Sphere001_6.geometry} material={materials['tree3.002']} />
        <mesh geometry={nodes.Sphere001_7.geometry} material={materials['tree3.004']} />
        <mesh geometry={nodes.Sphere001_8.geometry} material={materials['tree3.005']} />
        <mesh geometry={nodes.Sphere001_9.geometry} material={materials['tree3.001']} />
        <mesh geometry={nodes.Sphere001_10.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Sphere001_11.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Sphere001_12.geometry} material={materials['tree2.001']} />
        <mesh geometry={nodes.Sphere001_13.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Sphere001_14.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Sphere001_15.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.Sphere001_16.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Sphere001_17.geometry} material={materials['tree2.013']} />
        <mesh geometry={nodes.Sphere001_18.geometry} material={materials['Material.031']} />
        <mesh geometry={nodes.Sphere001_19.geometry} material={materials['Material.032']} />
        <mesh geometry={nodes.Sphere001_20.geometry} material={materials['tree3.031']} />
        <mesh geometry={nodes.Sphere001_21.geometry} material={materials['tree2.014']} />
        <mesh geometry={nodes.Sphere001_22.geometry} material={materials['tree2.015']} />
        <mesh geometry={nodes.Sphere001_23.geometry} material={materials['Material.041']} />
        <mesh geometry={nodes.Sphere001_24.geometry} material={materials['Material.042']} />
        <mesh geometry={nodes.Sphere001_25.geometry} material={materials['Material.043']} />
        <mesh geometry={nodes.Sphere001_26.geometry} material={materials['Material.044']} />
        <mesh geometry={nodes.Sphere001_27.geometry} material={materials['Material.045']} />
        <mesh geometry={nodes.Sphere001_28.geometry} material={materials['tree2.017']} />
        <mesh geometry={nodes.Sphere001_29.geometry} material={materials['Material.046']} />
        <mesh geometry={nodes.Sphere001_30.geometry} material={materials['tree3.037']} />
        <mesh geometry={nodes.Sphere001_31.geometry} material={materials['tree2.019']} />
        <mesh geometry={nodes.Sphere001_32.geometry} material={materials['tree3.038']} />
        <mesh geometry={nodes.Sphere001_33.geometry} material={materials['Material.047']} />
        <mesh geometry={nodes.Sphere001_34.geometry} material={materials['Material.048']} />
        <mesh geometry={nodes.Sphere001_35.geometry} material={materials['tree2.020']} />
        <mesh geometry={nodes.Sphere001_36.geometry} material={materials['Material.050']} />
        <mesh geometry={nodes.Sphere001_37.geometry} material={materials['Material.051']} />
        <mesh geometry={nodes.Sphere001_38.geometry} material={materials['tree2.025']} />
        <mesh geometry={nodes.Sphere001_39.geometry} material={materials['Material.052']} />
        <mesh geometry={nodes.Sphere001_40.geometry} material={materials['tree3.043']} />
        <mesh geometry={nodes.Sphere001_41.geometry} material={materials['tree3.044']} />
        <mesh geometry={nodes.Sphere001_42.geometry} material={materials['tree2.026']} />
      </group>
      <group position={[108.665, 26.595, -9.389]} scale={[0.456, 0.625, 0.456]}>
        <mesh geometry={nodes.Sphere002.geometry} material={materials['tree3.020']} />
        <mesh geometry={nodes.Sphere002_1.geometry} material={materials['wood1.022']} />
      </group>
      <mesh geometry={nodes.sign.geometry} material={materials['Material.079']} position={[119.443, 24.847, -16.963]} rotation={[Math.PI, -0.654, Math.PI]} scale={[0.716, 1, 1]} />
      <mesh geometry={nodes.tree4.geometry} material={nodes.tree4.material} position={[57.378, 19.762, -36.878]} rotation={[0, -1.204, 0]} scale={0.932}>
        <mesh geometry={nodes.Icosphere009.geometry} material={nodes.Icosphere009.material} position={[2.137, 11.495, -1.483]} rotation={[-0.032, 0.574, -0.085]} scale={[3.369, 2.991, 3.369]} />
        <mesh geometry={nodes.Icosphere010.geometry} material={nodes.Icosphere010.material} position={[-1.701, 12.002, 0]} rotation={[-0.057, -0.007, 0.354]} scale={[4.575, 4.062, 4.575]} />
        <mesh geometry={nodes.Icosphere011.geometry} material={nodes.Icosphere011.material} position={[0, 9.5, 0]} scale={[5.343, 4.743, 5.343]} />
      </mesh>
      <group position={[69.49, 23.313, -33.122]} scale={[0.456, 0.625, 0.456]}>
        <mesh geometry={nodes.Sphere005.geometry} material={materials['tree3.100']} />
        <mesh geometry={nodes.Sphere005_1.geometry} material={materials['wood1.130']} />
      </group>
      <mesh geometry={nodes.Cube072.geometry} material={nodes.Cube072.material} position={[90.869, 25.489, -0.864]} rotation={[0, -0.488, 0]} scale={[0.711, 0.983, 0.711]}>
        <mesh geometry={nodes.Icosphere012.geometry} material={nodes.Icosphere012.material} position={[-0.041, 11.082, 0.226]} rotation={[0, 0.454, 0]} scale={[4.953, 2.752, 7.241]} />
        <mesh geometry={nodes.Icosphere013.geometry} material={nodes.Icosphere013.material} position={[1.077, 9.451, -1.493]} rotation={[0, 0.454, 0]} scale={[7.137, 2.752, 10.434]} />
        <mesh geometry={nodes.Icosphere014.geometry} material={nodes.Icosphere014.material} position={[1.077, 8.181, -1.493]} rotation={[0.026, 0.479, 0.549]} scale={[6.871, 5.118, 9.836]} />
      </mesh>
      <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} position={[72.87, 21.61, -9.61]} rotation={[Math.PI, -0.452, Math.PI]} scale={[0.715, 1.476, 0.905]}>
        <mesh geometry={nodes.Cube076.geometry} material={nodes.Cube076.material} rotation={[0.667, -0.649, 0.325]} scale={[0.358, 0.196, 1.093]} />
        <mesh geometry={nodes.Icosphere015.geometry} material={nodes.Icosphere015.material} rotation={[0, -0.072, 0]} scale={[1.852, 0.812, 2.709]} />
        <mesh geometry={nodes.Icosphere016.geometry} material={nodes.Icosphere016.material} position={[-1.842, 0, 1.303]} scale={[4.864, 2.402, 4.541]} />
        <mesh geometry={nodes.Icosphere017.geometry} material={nodes.Icosphere017.material} scale={[4.415, 1.278, 5.099]} />
      </mesh>
      <group position={[80.633, 25.009, -6.86]} scale={[0.456, 0.625, 0.456]}>
        <mesh geometry={nodes.Sphere006.geometry} material={materials['tree3.142']} />
        <mesh geometry={nodes.Sphere006_1.geometry} material={materials['wood1.184']} />
      </group>
      <group position={[94.454, 24.54, -15.274]} rotation={[0.868, -1.459, 0.865]} scale={[0.303, 0.416, 0.303]}>
        <mesh geometry={nodes.Sphere007.geometry} material={materials['tree3.184']} />
        <mesh geometry={nodes.Sphere007_1.geometry} material={materials['wood1.238']} />
      </group>
      <mesh geometry={nodes.Cube077.geometry} material={nodes.Cube077.material} position={[53.503, 28.555, 9.642]} rotation={[0, -0.853, 0]} scale={[0.972, 1.345, 0.972]}>
        <mesh geometry={nodes.Icosphere018.geometry} material={nodes.Icosphere018.material} position={[-2.383, 17.625, 1.624]} rotation={[0, 0.454, 0]} scale={[4.953, 2.752, 7.241]} />
        <mesh geometry={nodes.Icosphere019.geometry} material={nodes.Icosphere019.material} position={[-1.265, 15.994, -0.095]} rotation={[0, 0.454, 0]} scale={[7.137, 2.752, 10.434]} />
        <mesh geometry={nodes.Icosphere020.geometry} material={nodes.Icosphere020.material} position={[-1.265, 11.839, -0.095]} rotation={[0, 0.454, 0]} scale={[8.846, 4.865, 12.934]} />
      </mesh>
      <mesh geometry={nodes.Cube078.geometry} material={nodes.Cube078.material} position={[45.719, 25.512, 3.943]} rotation={[2.838, -1.323, 2.871]} scale={[0.61, 0.843, 0.61]}>
        <mesh geometry={nodes.Icosphere021.geometry} material={nodes.Icosphere021.material} position={[-1.265, 11.839, -0.095]} rotation={[0, 0.454, 0]} scale={[8.846, 4.865, 12.934]} />
        <mesh geometry={nodes.Icosphere022.geometry} material={nodes.Icosphere022.material} position={[-1.265, 15.994, -0.095]} rotation={[0, 0.454, 0]} scale={[7.137, 2.752, 10.434]} />
        <mesh geometry={nodes.Icosphere023.geometry} material={nodes.Icosphere023.material} position={[-2.383, 17.625, 1.624]} rotation={[0, 0.454, 0]} scale={[4.953, 2.752, 7.241]} />
      </mesh>
      <group position={[18.546, 23.562, -10.359]} scale={[0.456, 0.625, 0.456]}>
        <mesh geometry={nodes.Sphere008.geometry} material={materials['tree3.226']} />
        <mesh geometry={nodes.Sphere008_1.geometry} material={materials['wood1.292']} />
      </group>
      <group position={[34.37, 25.516, -34.264]} scale={[0.7, 0.96, 0.7]}>
        <mesh geometry={nodes.Sphere009.geometry} material={materials['tree3.268']} />
        <mesh geometry={nodes.Sphere009_1.geometry} material={materials['wood1.346']} />
      </group>
      <mesh geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} position={[19.331, 21.61, -37.741]} rotation={[-Math.PI, 0.465, -Math.PI]} scale={[1.196, 2.467, 1.514]}>
        {/* <mesh geometry={nodes.Cube079_1.geometry} material={nodes.Cube079_1.material} rotation={[0.667, -0.649, 0.325]} scale={[0.358, 0.196, 1.093]} /> */}
        <mesh geometry={nodes.Icosphere024.geometry} material={nodes.Icosphere024.material} scale={[4.415, 1.278, 5.099]} />
        <mesh geometry={nodes.Icosphere025.geometry} material={nodes.Icosphere025.material} position={[-1.842, 0, 1.303]} scale={[4.864, 2.402, 4.541]} />
        <mesh geometry={nodes.Icosphere026.geometry} material={nodes.Icosphere026.material} rotation={[0, -0.072, 0]} scale={[1.852, 0.812, 2.709]} />
      </mesh>
      <mesh geometry={nodes.Cube080.geometry} material={nodes.Cube080.material} position={[-3.941, 30.098, -39.781]} rotation={[3.082, -0.277, 3.073]} scale={[0.61, 0.843, 0.61]}>
        <mesh geometry={nodes.Icosphere027.geometry} material={nodes.Icosphere027.material} position={[-1.721, 17.863, -0.777]} rotation={[0, 0.454, 0]} scale={[4.953, 2.752, 7.241]} />
        <mesh geometry={nodes.Icosphere028.geometry} material={nodes.Icosphere028.material} position={[-0.574, 15.92, -2.496]} rotation={[0, 0.454, 0]} scale={[7.137, 2.752, 10.434]} />
        <mesh geometry={nodes.Icosphere029.geometry} material={nodes.Icosphere029.material} position={[-0.966, 11.807, -1.135]} rotation={[0, 0.454, 0]} scale={[8.846, 4.865, 12.934]} />
      </mesh>
      <group position={[12.283, 25.545, -32.447]} scale={[0.456, 0.625, 0.456]}>
        <mesh geometry={nodes.Sphere010.geometry} material={materials['tree3.310']} />
        <mesh geometry={nodes.Sphere010_1.geometry} material={materials['wood1.400']} />
      </group>
      <mesh geometry={nodes.Cube081.geometry} material={nodes.Cube081.material} position={[9.639, 33.742, -50.998]} scale={[0.972, 1.345, 0.972]}>
        <mesh geometry={nodes.Icosphere030.geometry} material={nodes.Icosphere030.material} position={[-2.383, 17.625, 1.624]} rotation={[0, 0.454, 0]} scale={[4.953, 2.752, 7.241]} />
        <mesh geometry={nodes.Icosphere031.geometry} material={nodes.Icosphere031.material} position={[-1.265, 15.994, -0.095]} rotation={[0, 0.454, 0]} scale={[7.137, 2.752, 10.434]} />
        <mesh geometry={nodes.Icosphere032.geometry} material={nodes.Icosphere032.material} position={[-1.265, 11.839, -0.095]} rotation={[0, 0.454, 0]} scale={[8.846, 4.865, 12.934]} />
      </mesh>
      <group position={[-52.703, 33.942, -59.714]} scale={[0.7, 0.96, 0.7]}>
        <mesh geometry={nodes.Sphere011.geometry} material={materials['tree3.352']} />
        <mesh geometry={nodes.Sphere011_1.geometry} material={materials['wood1.454']} />
      </group>
      <group position={[-40.077, 29.401, -17.036]} scale={[0.581, 0.796, 0.581]}>
        <mesh geometry={nodes.Sphere012.geometry} material={materials['tree3.394']} />
        <mesh geometry={nodes.Sphere012_1.geometry} material={materials['wood1.508']} />
      </group>
      <mesh geometry={nodes.Cube082.geometry} material={nodes.Cube082.material} position={[-49.93, 38.113, -74.185]} rotation={[0, 0.149, 0]} scale={[1.218, 1.685, 1.218]}>
        <mesh geometry={nodes.Icosphere033.geometry} material={nodes.Icosphere033.material} position={[-1.265, 11.839, -0.095]} rotation={[0, 0.454, 0]} scale={[8.846, 4.865, 12.934]} />
        <mesh geometry={nodes.Icosphere034.geometry} material={nodes.Icosphere034.material} position={[-1.265, 15.994, -0.095]} rotation={[0, 0.454, 0]} scale={[7.137, 2.752, 10.434]} />
        <mesh geometry={nodes.Icosphere035.geometry} material={nodes.Icosphere035.material} position={[-2.383, 17.625, 1.624]} rotation={[0, 0.454, 0]} scale={[4.953, 2.752, 7.241]} />
      </mesh>
      <mesh geometry={nodes.Cylinder003.geometry} material={nodes.Cylinder003.material} position={[-54.397, 24.397, -23.448]} rotation={[-0.106, 0.303, 0]} scale={[1.196, 2.467, 1.514]}>
        <mesh geometry={nodes.Cube083.geometry} material={nodes.Cube083.material} rotation={[0.667, -0.649, 0.325]} scale={[0.358, 0.196, 1.093]} />
        <mesh geometry={nodes.Icosphere036.geometry} material={nodes.Icosphere036.material} rotation={[0, -0.072, 0]} scale={[1.852, 0.812, 2.709]} />
        <mesh geometry={nodes.Icosphere037.geometry} material={nodes.Icosphere037.material} position={[-1.842, 0, 1.303]} scale={[4.864, 2.402, 4.541]} />
      </mesh>
      <group position={[-68.392, 36.227, -33.918]} scale={[1.046, 1.434, 1.046]}>
        <mesh geometry={nodes.Sphere013.geometry} material={materials['tree3.436']} />
        <mesh geometry={nodes.Sphere013_1.geometry} material={materials['wood1.562']} />
      </group>
      <mesh geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} position={[-25.867, 25.899, -35.798]} rotation={[-0.102, 0.14, -0.017]} scale={[0.748, 1.543, 0.947]}>
        <mesh geometry={nodes.Cube084.geometry} material={nodes.Cube084.material} rotation={[0.667, -0.649, 0.325]} scale={[0.358, 0.196, 1.093]} />
        <mesh geometry={nodes.Icosphere038.geometry} material={nodes.Icosphere038.material} position={[-1.842, 0, 1.303]} scale={[4.864, 2.402, 4.541]} />
        <mesh geometry={nodes.Icosphere039.geometry} material={nodes.Icosphere039.material} rotation={[0, -0.072, 0]} scale={[1.852, 0.812, 2.709]} />
      </mesh>
      <group position={[-82.419, 36.227, -66.099]} rotation={[0, 0.107, 0]} scale={[1.046, 1.434, 1.046]}>
        <mesh geometry={nodes.Sphere014.geometry} material={materials['tree3.478']} />
        <mesh geometry={nodes.Sphere014_1.geometry} material={materials['wood1.616']} />
      </group>
      <mesh geometry={nodes.Cube085.geometry} material={nodes.Cube085.material} position={[-90.041, 26.457, -58.582]} scale={1.385}>
        <mesh geometry={nodes.Icosphere040.geometry} material={nodes.Icosphere040.material} position={[2.137, 11.495, -1.483]} rotation={[-0.032, 0.574, -0.085]} scale={[3.369, 2.991, 3.369]} />
        <mesh geometry={nodes.Icosphere041.geometry} material={nodes.Icosphere041.material} position={[-1.701, 12.002, 0]} rotation={[-0.057, -0.007, 0.354]} scale={[4.575, 4.062, 4.575]} />
        <mesh geometry={nodes.Icosphere042.geometry} material={nodes.Icosphere042.material} position={[0, 9.5, 0]} scale={[5.343, 4.743, 5.343]} />
      </mesh>
      <mesh geometry={nodes.Cube086.geometry} material={nodes.Cube086.material} position={[-34.455, 26.457, -55.165]} rotation={[0, 0.216, 0]} scale={0.942}>
        <mesh geometry={nodes.Icosphere043.geometry} material={nodes.Icosphere043.material} position={[0, 11.997, 0]} scale={[5.343, 6.619, 5.343]} />
        <mesh geometry={nodes.Icosphere044.geometry} material={nodes.Icosphere044.material} position={[-1.701, 15.489, 0]} rotation={[-0.057, -0.007, 0.354]} scale={[4.828, 5.495, 4.582]} />
        <mesh geometry={nodes.Icosphere045.geometry} material={nodes.Icosphere045.material} position={[2.137, 14.781, -1.483]} rotation={[-0.032, 0.574, -0.085]} scale={[3.386, 4.163, 3.37]} />
      </mesh>
      <mesh geometry={nodes.Cube087.geometry} material={nodes.Cube087.material} position={[-106.048, 37.341, -185.283]} rotation={[2.846, 1.342, -2.748]} scale={[1.218, 1.685, 1.218]}>
        <mesh geometry={nodes.Icosphere046.geometry} material={nodes.Icosphere046.material} position={[-1.804, 17.451, -1.072]} rotation={[0, 0.454, 0]} scale={[4.953, 2.752, 7.241]} />
        <mesh geometry={nodes.Icosphere047.geometry} material={nodes.Icosphere047.material} position={[-0.884, 15.88, -1.871]} rotation={[0, 0.454, 0]} scale={[7.137, 2.752, 10.434]} />
        <mesh geometry={nodes.Icosphere048.geometry} material={nodes.Icosphere048.material} position={[-1.266, 11.839, -0.095]} rotation={[0, 0.454, 0]} scale={[8.846, 4.865, 12.934]} />
      </mesh>
      <mesh geometry={nodes.Cube088.geometry} material={nodes.Cube088.material} position={[-104.921, 34.149, -164.088]} rotation={[0.041, -0.207, -0.012]} scale={[0.809, 1.12, 0.809]}>
        <mesh geometry={nodes.Icosphere049.geometry} material={nodes.Icosphere049.material} position={[-0.743, 9.007, -0.031]} rotation={[0, 0.454, 0]} scale={[8.846, 4.865, 12.934]} />
        <mesh geometry={nodes.Icosphere050.geometry} material={nodes.Icosphere050.material} position={[-0.362, 13.048, -1.807]} rotation={[0, 0.454, 0]} scale={[7.137, 2.752, 10.434]} />
      </mesh>
      <group position={[-92.849, 36.919, -170.677]} scale={[1.08, 1.481, 1.08]}>
        <mesh geometry={nodes.Sphere015.geometry} material={materials['tree3.520']} />
        <mesh geometry={nodes.Sphere015_1.geometry} material={materials['wood1.670']} />
      </group>
      <mesh geometry={nodes.Cube089.geometry} material={nodes.Cube089.material} position={[-100.106, 37, -124.674]} rotation={[2.973, 1.198, -2.997]} scale={[0.993, 1.373, 0.993]}>
        <mesh geometry={nodes.Icosphere052.geometry} material={nodes.Icosphere052.material} position={[-0.743, 9.007, -0.031]} rotation={[0, 0.454, 0]} scale={[8.846, 4.865, 12.934]} />
      </mesh>
      <mesh geometry={nodes.Cube091.geometry} material={nodes.Cube091.material} position={[-100.106, 37, -124.674]} rotation={[2.973, 1.198, -2.997]} scale={[0.993, 1.373, 0.993]}>
        <mesh geometry={nodes.Icosphere054.geometry} material={nodes.Icosphere054.material} position={[-0.86, 13.1, -0.521]} rotation={[0, 0.454, 0]} scale={[7.137, 3.719, 10.45]} />
      </mesh>
      <mesh geometry={nodes.Cube092.geometry} material={nodes.Cube092.material} position={[-60.922, 38.113, -146.668]} rotation={[0, 0.149, 0]} scale={[1.218, 1.685, 1.218]}>
        <mesh geometry={nodes.Icosphere051.geometry} material={nodes.Icosphere051.material} position={[-1.265, 11.839, -0.095]} rotation={[0, 0.454, 0]} scale={[8.846, 4.865, 12.934]} />
        <mesh geometry={nodes.Icosphere053.geometry} material={nodes.Icosphere053.material} position={[0.346, 10.814, 1.428]} rotation={[0, -0.149, 0]} scale={[6.925, 3.08, 6.925]} />
      </mesh>
      <group position={[-54.864, 39.803, -123.73]} scale={[1.31, 1.797, 1.31]}>
        <mesh geometry={nodes.Sphere016.geometry} material={materials['tree3.562']} />
        <mesh geometry={nodes.Sphere016_1.geometry} material={materials['wood1.724']} />
      </group>
      <mesh geometry={nodes.Cylinder005.geometry} material={nodes.Cylinder005.material} position={[-59.678, 30.84, -170.15]} rotation={[0, 1.472, 0]} scale={[1.175, 2.424, 1.487]}>
        <mesh geometry={nodes.Cube090.geometry} material={nodes.Cube090.material} rotation={[0.667, -0.649, 0.325]} scale={[0.358, 0.196, 1.093]} />
        <mesh geometry={nodes.Icosphere055.geometry} material={nodes.Icosphere055.material} rotation={[0, -0.072, 0]} scale={[1.852, 0.812, 2.709]} />
        <mesh geometry={nodes.Icosphere056.geometry} material={nodes.Icosphere056.material} position={[-1.842, 0, 1.303]} scale={[4.864, 2.402, 4.541]} />
        <mesh geometry={nodes.Icosphere057.geometry} material={nodes.Icosphere057.material} scale={[4.415, 1.278, 5.099]} />
      </mesh>
      <group position={[-61.041, 43.253, -156.592]} rotation={[Math.PI, -0.503, Math.PI]} scale={[1.31, 1.797, 1.31]}>
        <mesh geometry={nodes.Sphere017.geometry} material={materials['tree3.604']} />
        <mesh geometry={nodes.Sphere017_1.geometry} material={materials['wood1.778']} />
      </group>
      <mesh geometry={nodes.Cube093.geometry} material={nodes.Cube093.material} position={[-67.99, 38.113, -214.435]} rotation={[0.359, 1.175, -0.303]} scale={[1.218, 1.685, 1.218]}>
        <mesh geometry={nodes.Icosphere058.geometry} material={nodes.Icosphere058.material} position={[0.346, 10.814, 1.428]} rotation={[0, -0.149, 0]} scale={[6.925, 3.08, 6.925]} />
        <mesh geometry={nodes.Icosphere059.geometry} material={nodes.Icosphere059.material} position={[-1.265, 11.839, -0.095]} rotation={[0, 0.454, 0]} scale={[8.846, 4.865, 12.934]} />
      </mesh>
      <group position={[-24.469, 37.665, -249.346]} scale={[1.08, 1.481, 1.08]}>
        <mesh geometry={nodes.Sphere018.geometry} material={materials['tree3.646']} />
        <mesh geometry={nodes.Sphere018_1.geometry} material={materials['wood1.832']} />
      </group>
      <mesh geometry={nodes.Cube094.geometry} material={nodes.Cube094.material} position={[75.347, 37, -197.465]} rotation={[2.973, 1.198, -2.997]} scale={[0.993, 1.373, 0.993]}>
        <mesh geometry={nodes.Icosphere060.geometry} material={nodes.Icosphere060.material} position={[-0.86, 13.1, -0.521]} rotation={[0, 0.454, 0]} scale={[7.137, 3.719, 10.45]} />
      </mesh>
      <mesh geometry={nodes.Cube095.geometry} material={nodes.Cube095.material} position={[75.347, 37, -197.465]} rotation={[2.973, 1.198, -2.997]} scale={[0.993, 1.373, 0.993]}>
        <mesh geometry={nodes.Icosphere061.geometry} material={nodes.Icosphere061.material} position={[-0.743, 9.007, -0.031]} rotation={[0, 0.454, 0]} scale={[8.846, 4.865, 12.934]} />
      </mesh>
      <mesh geometry={nodes.Cube096.geometry} material={nodes.Cube096.material} position={[49.533, 37.5, -223.738]} rotation={[0, 0.149, 0]} scale={[1.218, 1.685, 1.218]}>
        <mesh geometry={nodes.Icosphere062.geometry} material={nodes.Icosphere062.material} position={[0.346, 10.814, 1.428]} rotation={[0, -0.149, 0]} scale={[6.925, 3.08, 6.925]} />
        <mesh geometry={nodes.Icosphere063.geometry} material={nodes.Icosphere063.material} position={[-1.265, 11.839, -0.095]} rotation={[0, 0.454, 0]} scale={[8.846, 4.865, 12.934]} />
      </mesh>
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.033']} position={[-26.623, 39.769, 2.926]} rotation={[0, 1.326, 0]}>
        <mesh geometry={nodes.Cube.geometry} material={materials['Material.023']} position={[0, -5.811, 0]} />
        <mesh geometry={nodes.Cube001.geometry} material={materials['Material.028']} position={[3.549, -15.37, 0]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh geometry={nodes.Cube002.geometry} material={materials['Material.029']} position={[10.33, -6.908, 0]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[8.548, -3.561, -4.751]} />
        <mesh geometry={nodes.Cube004_10.geometry} material={nodes.Cube004_10.material} position={[9.824, -11.825, -6.81]} />
        <mesh geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[9.824, -11.825, 7.342]} />
        {/* <mesh geometry={nodes.Cube007_1.geometry} material={nodes.Cube007_1.material} position={[1.603, 3.373, 5.899]} /> */}
        <mesh geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} position={[8.548, 3.785, -4.751]} />
        <mesh geometry={nodes.Cube009.geometry} material={nodes.Cube009.material} position={[0, -4.875, 8.791]} />
        <mesh geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} position={[3.066, -11.798, 8.791]} />
        <mesh geometry={nodes.Cube011.geometry} material={nodes.Cube011.material} position={[6.147, -5.191, 3.688]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes.Cube012.geometry} material={nodes.Cube012.material} position={[6.147, -12.827, -3.446]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes.Cube013.geometry} material={nodes.Cube013.material} position={[13.982, -16.862, 3.672]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes.Cube014.geometry} material={nodes.Cube014.material} position={[12.548, -15.875, 3.672]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes.Cube015.geometry} material={nodes.Cube015.material} position={[13.676, -15.583, 0.434]} />
        <mesh geometry={nodes.Cube016.geometry} material={nodes.Cube016.material} position={[13.676, -15.583, 6.928]} />
        <mesh geometry={nodes.Cube017.geometry} material={nodes.Cube017.material} position={[9.824, -11.825, -0.05]} />
        <mesh geometry={nodes.Cube018.geometry} material={nodes.Cube018.material} position={[15.681, -14.048, -3.029]} />
        <mesh geometry={nodes.Cube019.geometry} material={nodes.Cube019.material} position={[15.681, -14.048, -5.195]} />
        <mesh geometry={nodes.Cube020.geometry} material={nodes.Cube020.material} position={[15.681, -14.048, -7.479]} />
        <mesh geometry={nodes.Cube021.geometry} material={nodes.Cube021.material} position={[15.686, -15.453, -5.369]} />
        <mesh geometry={nodes.Cube022.geometry} material={nodes.Cube022.material} position={[9.666, -15.497, -14.172]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes.Cube023.geometry} material={nodes.Cube023.material} position={[7.557, -14.093, -14.166]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes.Cube024.geometry} material={nodes.Cube024.material} position={[9.841, -14.093, -14.166]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes.Cube025.geometry} material={nodes.Cube025.material} position={[12.007, -14.093, -14.166]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes.Cube059.geometry} material={nodes.Cube059.material} position={[6.61, -2.889, 3.575]} rotation={[0.874, 1.535, -0.88]} />
        <mesh geometry={nodes.Cube060.geometry} material={nodes.Cube060.material} position={[6.61, -10.578, -3.629]} rotation={[0.874, 1.535, -0.88]} />
        {/* <mesh geometry={nodes.Cube061_1.geometry} material={nodes.Cube061_1.material} position={[2.509, -9.569, 9.026]} rotation={[0.027, -0.023, -0.005]} /> */}
        {/* <mesh geometry={nodes.Cube062_1.geometry} material={materials['Material.090']} position={[6.447, -11.149, 3.876]} /> */}
      </mesh>
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[-2.401, 21.61, -4.256]} rotation={[0, 0.717, 0]} scale={[0.921, 1.899, 1.166]}>
        {/* <mesh geometry={nodes.Cube073_1.geometry} material={nodes.Cube073_1.material} rotation={[0.667, -0.649, 0.325]} scale={[0.358, 0.196, 1.093]} /> */}
        <mesh geometry={nodes.Icosphere.geometry} material={nodes.Icosphere.material} scale={[4.415, 1.278, 5.099]} />
        <mesh geometry={nodes.Icosphere001.geometry} material={nodes.Icosphere001.material} position={[-1.842, 0, 1.303]} scale={[4.864, 2.402, 4.541]} />
        <mesh geometry={nodes.Icosphere002.geometry} material={nodes.Icosphere002.material} rotation={[0, -0.072, 0]} scale={[1.852, 0.812, 2.709]} />
      </mesh>
      <mesh geometry={nodes.Cube075.geometry} material={nodes.Cube075.material} position={[14.483, 20.77, 0.569]} scale={1.385}>
        <mesh geometry={nodes.Icosphere006.geometry} material={nodes.Icosphere006.material} position={[0, 9.5, 0]} scale={[5.343, 4.743, 5.343]} />
        <mesh geometry={nodes.Icosphere007.geometry} material={nodes.Icosphere007.material} position={[-1.701, 12.002, 0]} rotation={[-0.057, -0.007, 0.354]} scale={[4.575, 4.062, 4.575]} />
        <mesh geometry={nodes.Icosphere008.geometry} material={nodes.Icosphere008.material} position={[2.137, 11.495, -1.483]} rotation={[-0.032, 0.574, -0.085]} scale={[3.369, 2.991, 3.369]} />
      </mesh>
      <mesh geometry={nodes.Cube074.geometry} material={nodes.Cube074.material} position={[3.128, 31.448, 9.426]} scale={[0.972, 1.345, 0.972]}>
        <mesh geometry={nodes.Icosphere003.geometry} material={nodes.Icosphere003.material} position={[-1.265, 11.839, -0.095]} rotation={[0, 0.454, 0]} scale={[8.846, 4.865, 12.934]} />
        <mesh geometry={nodes.Icosphere004.geometry} material={nodes.Icosphere004.material} position={[-1.265, 15.994, -0.095]} rotation={[0, 0.454, 0]} scale={[7.137, 2.752, 10.434]} />
        <mesh geometry={nodes.Icosphere005.geometry} material={nodes.Icosphere005.material} position={[-2.383, 17.625, 1.624]} rotation={[0, 0.454, 0]} scale={[4.953, 2.752, 7.241]} />
      </mesh>
      <mesh geometry={nodes.Cube034.geometry} material={materials['Material.039']} position={[-102.431, 37.443, -89.954]} rotation={[0, 0.425, 0]}>
        <mesh geometry={nodes.Cube027.geometry} material={nodes.Cube027.material} position={[13.666, -8.406, 8.169]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh geometry={nodes.Cube028.geometry} material={nodes.Cube028.material} position={[13.666, -8.406, 10.427]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh geometry={nodes.Cube029.geometry} material={nodes.Cube029.material} position={[13.66, -9.795, 8.341]} rotation={[Math.PI, 0, Math.PI]} />
        {/* <mesh geometry={nodes.Cube030_1.geometry} material={nodes.Cube030_1.material} position={[14.34, -9.523, -9.129]} /> */}
        <mesh geometry={nodes.Cube031.geometry} material={nodes.Cube031.material} position={[14.335, -8.134, -11.215]} />
        <mesh geometry={nodes.Cube032.geometry} material={nodes.Cube032.material} position={[14.335, -8.134, -8.956]} />
        <mesh geometry={nodes.Cube033.geometry} material={nodes.Cube033.material} position={[14.335, -8.134, -6.814]} />
        <mesh geometry={nodes.Cube035.geometry} material={nodes.Cube035.material} position={[11.481, -8.868, 5.888]} />
        <mesh geometry={nodes.Cube036.geometry} material={nodes.Cube036.material} position={[11.481, -8.868, -0.006]} />
        <mesh geometry={nodes.Cube037.geometry} material={nodes.Cube037.material} position={[10.533, -9.134, 2.932]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes.Cube038.geometry} material={nodes.Cube038.material} position={[11.738, -10.029, 2.932]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes.Cube039.geometry} material={nodes.Cube039.material} position={[0.619, 5.779, -6.192]} />
        <mesh geometry={nodes.Cube040.geometry} material={materials['Material.067']} position={[6.887, -6.367, -4.33]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh geometry={nodes.Cube041.geometry} material={materials['Material.072']} position={[6.887, -7.52, -2.4]} rotation={[-Math.PI / 2, 0, Math.PI]} />
        {/* <mesh geometry={nodes.Cube042_1.geometry} material={materials['Material.075']} position={[6.887, -7.52, -6.04]} rotation={[-Math.PI / 2, 0, Math.PI]} /> */}
        {/* <mesh geometry={nodes.Cube046_1.geometry} material={nodes.Cube046_1.material} position={[5.499, -3.35, -4.584]} rotation={[1.686, 1.52, -1.707]} /> */}
        <mesh geometry={nodes.Cube050.geometry} material={materials['Material.038']} position={[2.979, -8.676, 0]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh geometry={nodes.Cube051.geometry} material={materials['Material.039']} />
      </mesh>
      <mesh geometry={nodes.Cube054.geometry} material={materials['Material.087']} position={[-83.189, 40.547, -193.789]} rotation={[0, -0.403, 0]}>
        <mesh geometry={nodes.Cube026.geometry} material={materials['Material.087']} />
        {/* <mesh geometry={nodes.Cube043_1.geometry} material={materials['Material.088']} position={[3.186, -9.278, 0]} rotation={[Math.PI, 0, Math.PI]} /> */}
        {/* <mesh geometry={nodes.Cube047_1.geometry} material={nodes.Cube047_1.material} position={[0.662, 6.181, 6.111]} /> */}
        {/* <mesh geometry={nodes.Cube048_1.geometry} material={nodes.Cube048_1.material} position={[12.553, -10.726, -0.112]} rotation={[0, 1.571, 0]} /> */}
        <mesh geometry={nodes.Cube049.geometry} material={nodes.Cube049.material} position={[11.265, -9.768, -0.112]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes.Cube052.geometry} material={nodes.Cube052.material} position={[12.278, -9.484, -3.255]} />
        {/* <mesh geometry={nodes.Cube053_1.geometry} material={nodes.Cube053_1.material} position={[12.278, -9.484, 3.048]} /> */}
      </mesh>
      <mesh geometry={nodes.Cube044.geometry} material={materials['Material.089']} position={[-7.685, 40.251, -241.877]} rotation={[0, -1.566, 0]}>
        <mesh geometry={nodes.Cube045.geometry} material={nodes.Cube045.material} position={[-0.793, -3.718, 8.535]} rotation={[0.05, 0.006, -0.018]} />
        <mesh geometry={nodes.Cube055.geometry} material={nodes.Cube055.material} position={[7.572, -10.095, 13.205]} rotation={[-Math.PI, 1.375, -Math.PI]} scale={[0.327, 3.665, 0.712]} />
        <mesh geometry={nodes.Cube056.geometry} material={nodes.Cube056.material} position={[5.059, -10.095, 13.744]} rotation={[-Math.PI, 1.375, -Math.PI]} scale={[0.327, 3.665, 0.712]} />
        <mesh geometry={nodes.Cube057.geometry} material={nodes.Cube057.material} position={[2.408, -10.095, 14.313]} rotation={[-Math.PI, 1.375, -Math.PI]} scale={[0.327, 3.665, 0.712]} />
        <mesh geometry={nodes.Cube058.geometry} material={nodes.Cube058.material} position={[4.855, -11.892, 13.78]} rotation={[-Math.PI, 1.375, -Math.PI]} scale={[0.16, 0.512, 2.518]} />
        <mesh geometry={nodes.Cube063.geometry} material={materials['Material.091']} position={[0, 1.817, 0]} />
        <mesh geometry={nodes.Cube064.geometry} material={nodes.Cube064.material} position={[-0.681, 6.145, 6.176]} />
        <mesh geometry={nodes.Cube065.geometry} material={materials['Material.091']} position={[0, 1.817, 0]} />
        <mesh geometry={nodes.Cube066.geometry} material={nodes.Cube066.material} position={[14.473, -10.974, 1.093]} />
        <mesh geometry={nodes.Cube067.geometry} material={nodes.Cube067.material} position={[14.473, -10.974, -6.529]} />
        {/* <mesh geometry={nodes.Cube068_1.geometry} material={nodes.Cube068_1.material} position={[13.248, -11.318, -2.729]} rotation={[0, 1.571, 0]} /> */}
        <mesh geometry={nodes.Cube069.geometry} material={nodes.Cube069.material} position={[14.805, -12.476, -2.729]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes.Cube070.geometry} material={nodes.Cube070.material} position={[20.079, -9.623, 18.249]} rotation={[1.659, 0.023, 3.022]} scale={[0.265, 5.786, 1.209]} />
        <mesh geometry={nodes.Cube071.geometry} material={nodes.Cube071.material} position={[19.971, -11.541, 21.623]} rotation={[-3.105, 1.444, 3.064]} scale={[0.463, 2.157, 0.335]} />
      </mesh>
      <group position={[-102.02, 36.267, -94.977]} rotation={[0, -1.395, 0]} scale={[15.341, 11.353, 9.82]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube004_3.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube004_4.geometry} material={materials['tree1.013']} />
        <mesh geometry={nodes.Cube004_5.geometry} material={materials['tree1.014']} />
        <mesh geometry={nodes.Cube004_6.geometry} material={materials['Material.037']} />
        <mesh geometry={nodes.Cube004_7.geometry} material={materials.tree3} />
        <mesh geometry={nodes.Cube004_8.geometry} material={materials['Material.049']} />
        <mesh geometry={nodes.Cube004_9.geometry} material={materials['Material.053']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/main_ground.gltf')
